### ISSUE TITLE
qHT for 1 species communities

### ISSUE THREAD

**Issue by annakat** [ShanKothari/DecomposingFD#3]
I believe Ht for 1 species communities should be defined as Ht = 0 (see Scheiner et al. 2016 note below eqn 3: "qHT = 0, if all dij =0"). 

Doesn't the current code set Ht = 1?
if(q==1){
    fijlog<-fij*log(fij)
    fijlog[is.na(fijlog)]<-0
    Ht<-exp(-1*sum(fijlog))
  }

It follows that currently qDT/qET = 1.62, instead of qDT/qET = 1 (for 1 species comm).
The result for qDTM is correct.

**Comment by ShanKothari** [comment]
Thank you! I've just fixed this.
